autentikasi/urls.py
from django.urls import path
from . import views

app_name = 'autentikasi'

urlpatterns = [
    path('login/', views.loginPage, name='login'),
    path('register/', views.registerPage, name='register'),
    path('logout/', views.logoutUser, name="logout"),
    path('', views.autentikasi, name='autentikasi'),
]

kepepetpergi/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('berita/', include('berita.urls')),
    path('tambahData/', include('tambahData.urls')),
    path('pencarian/', include('pencarian.urls')),
    path('status/', include('status.urls')),
    path('formSaran/', include('formSaran.urls')),
    path('autentikasi/', include('autentikasi.urls')),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

pencarian/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.pencarian, name='pencarian'),
]

pencarian/models.py
from django.db import models

# Create your models here.

pencarian/forms.py
from django import forms
from main.models import Provinsi

class PencarianForm(forms.ModelForm):
    class Meta:
        model = Provinsi
        fields = ['nama']
        widgets = {
            'nama':forms.TextInput(attrs={
                'class':'form-control',
                'placeholder' : 'Masukkan nama provinsi',
            })
        }

pencarian/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from main.models import *
from .forms import PencarianForm
from pencarian import forms
from main import models
from django.contrib import messages

# Create your views here.

def pencarian(request):
    data_verified = VerifiedInfo.objects.all()
    form = PencarianForm(request.GET)
    context = {
        'form': PencarianForm(),
        'data' : data_verified,
    }

    if request.method == 'POST':
        found = False
        query = str(request.POST['nama'])
        for info in data_verified:
            if query.lower() in str(info.info_id.nama_provinsi).lower():
                context['info'] = info.info_id
                messages.success(request, ("Data '" + query + "' berhasil ditemukan! ✅"))
                found = True
                return render(request, 'pencarian/pencarian.html', context)
            
        if found == False:   
            messages.warning(request, "❌ OOPS ❌")
            messages.warning(request, (" Data '" + query + "' belum tersedia atau terdapat kesalahan ejaan nama provinsi. Mohon diperiksa kembali 🙏🏻"))
            return render(request, 'pencarian/pencarian.html', context)
                
    return render(request, 'pencarian/pencarian.html', context)

pencarian/templates/pencarian/pencarian.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Pencarian</title>
{% endblock meta %}

{% block footer_style %}relative{% endblock %}

{% block content %}

<div class="d-flex flex-column my-3 berita-content">
  <h1 style="text-align: center;"> Pencarian </h1>

  <div class="card my-5 border-custom">
    <div class="card-body p-5">
      <h5 class="card-title">Nama Provinsi</h5>
          <form method="post" action="{% url 'pencarian' %}">
            {% csrf_token %}
            {% for form in form %}
              {{ form }}
            {% endfor %}
            <br>
              <button class="btn btn-primary float-right" type="submit">Search</button>
            <br>
          </form>

    </div>
  </div>

  {% for message in messages %}
    <h3 id="messages" style="background-color: rgb(185, 185, 185); color:black; text-align: center;">{{ message }}</h3>
  {% endfor %}

  <br><br>

  {% if info.nama_provinsi.nama != null %}
  <h1 style="text-align: center;"> Hasil Pencarian </h1> 
  <div class="card my-5 border-custom">
    <div class="card-body p-5">
      <h3 class="card-title" style="text-align: center;">{{ info.nama_provinsi.nama}}</h3>
      <br>
      <div class="card my-3 border-custom2">
        <div class="card-body child-card">
          {% if user.is_authenticated == True %}
          <h4><strong>Protokol Kesehatan</strong></h4>
          <h4 style="text-align: justify;">{{ info.protokol_kesehatan }}</h4>
          {% else %}
          <h4 style="text-align: justify;">Harap melakukan Login terlebih dulu untuk dapat melihat protokol kesehatan secara lengkap.<a href="{% url 'autentikasi:login' %}" class="ml-2">Login sekarang!</a></h4>
          {% endif %}
          <br>
        {% for website in info.website_pemda.all %}
          <br>
          <h4>Website: <br><li><a href="{{ website.alamat }}" target="_blank">{{ website.alamat }}</a></li></h4>
        {% endfor %}
          <br>
        {% for email in info.email_pemda.all %}
          <h4>Alamat Email: <br><li>{{ email.email }}</li></h4>
        {% endfor %}
          <br>
        {% for telpon in info.telpon_pemda.all %}
          <h4>No. Telpon: <br><li>{{ telpon.nomor_telpon }}</li><h4>
        {% endfor %}
        </div>
      </div>
    </div>
  </div>
  {% endif %}

</div>

{% endblock content %}