autentikasi/urls.py
from django.urls import path
from . import views

app_name = 'autentikasi'

urlpatterns = [
    path('login/', views.loginPage, name='login'),
    path('register/', views.registerPage, name='register'),
    path('logout/', views.logoutUser, name="logout"),
    path('', views.autentikasi, name='autentikasi'),
]

kepepetpergi/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('berita/', include('berita.urls')),
    path('tambahData/', include('tambahData.urls')),
    path('pencarian/', include('pencarian.urls')),
    path('status/', include('status.urls')),
    path('formSaran/', include('formSaran.urls')),
    path('autentikasi/', include('autentikasi.urls')),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

autentikasi/models.py
from django.db import models

# Create your models here.

autentikasi/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class CreateUserForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']

autentikasi/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm

from django.http import HttpResponse
from django.forms import inlineformset_factory
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Create your views here.

from .models import *
from .forms import CreateUserForm

def loginPage(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is None:
            User = get_user_model()
            user_queryset = User.objects.all().filter(email__iexact=username)
            if user_queryset:
                username = user_queryset[0].username
                user = authenticate(username=username, password=password)

        if user is not None:
            login(request, user)
            request.session['username'] = request.user.username
            return redirect('main:home')
        else:
            messages.info(request, 'Username OR password is incorrect')

    response = {}
    return render(request, 'autentikasi/login.html', response)

@login_required(login_url='autentikasi:login')
def logoutUser(request):
    logout(request)
    return redirect('/')

def registerPage(request):
    form = CreateUserForm()

    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(request, 'Account was created for ' + user)

            return redirect('autentikasi:login')

    response = {'form':form}
    return render(request, 'autentikasi/register.html', response)

def autentikasi(request):
    response = {}
    return render(request, 'main/home.html', response)

autentikasi/templates/autentikasi/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="container containerA h-100">
    <div class="d-flex justify-content-center h-100">
        <div class="user_card">
            <div class="d-flex justify-content-center">

                
                <h1 id="form-title"><br>LOGIN</h1>
            </div>
            <br>
            <div class="d-flex justify-content-center form_container">
                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fa fa-user-circle"></i></span>
                            <input type="text" name="username" placeholder="Enter username or email " class="form-control">
                        </div>
                    </div>
                    <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fa fa-unlock"></i></span>
                            <input type="password" name="password" placeholder="Enter password" class="form-control" >
                        </div>
                    </div>
                        <div class="justify-content-center">
                            <br>
                            <input class="btn login_btn" type="submit" value="Login">
                        </div>
                </form>

            </div>

            <br>
            {% for message in messages %}
                <p id="messages">{{message}}</p>
            {% endfor %}
    
            <div class="mt-4">
                <div class="d-flex justify-content-center links">
                    Don't have an account yet? <a href="{% url 'autentikasi:register' %}" class="ml-2">Register now!</a>
                </div>
                <br>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

autentikasi/templates/autentikasi/register.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="container containerA h-100">
    <div class="d-flex justify-content-center h-100">
        <div class="user_card">
            <div class="d-flex justify-content-center">
                <h1 id="form-title"><br>REGISTER</h1>
            </div>
            <br>
            <div class="d-flex justify-content-center form_container">                
                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="input-group aa mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text" ><i class="fa fa-user-circle"></i></span>
                            {{form.username}}
                        </div>
                        <small id="hint_id_username" class="form-text text-muted">Required. Letters, digits and @/./+/-/_ only.</small>
                        
                    </div>
                    <div class="input-group aa mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fa fa-id-card-o"></i></span>
                            {{form.first_name}}
                        </div>
                        
                    </div>
                    <div class="input-group aa mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fa fa-id-card-o"></i></span>
                            {{form.last_name}}
                        </div>
                        
                    </div>
                    <div class="input-group aa mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fa fa-envelope"></i></span>
                            {{form.email}}
                        </div>
                        
                    </div>
                    <div class="input-group aa mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fa fa-unlock"></i></span>
                            {{form.password1}}
                        </div>
                        <small id="hint_id_password1" class="form-text text-muted">must contain at least 8 characters.<br>can’t be a commonly used password.<br>can’t be entirely numeric.</small>
                    </div>
                    
                    <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fa fa-unlock"></i></span>
                            {{form.password2}}
                        </div>
                        <small id="hint_id_password2" class="form-text text-muted">Enter the same password as before</small>
                    </div>

                       <div class="justify-content-center">
                           <br>
                         <input class="btn login_btn" type="submit" value="Register Account">
                       </div>
                </form>
            </div>

            {{form.errors}}
    
            <div class="mt-4">
                <div class="d-flex justify-content-center links">
                    Already have an account? <a href="{% url 'autentikasi:login' %}" class="ml-2">Login</a>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    /* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
//We start indexing at one because CSRF_token is considered and input field 
*/

//Query All input fields
var form_fields = document.getElementsByTagName('input')
form_fields[1].placeholder='Username..';
form_fields[2].placeholder='First name..';
form_fields[3].placeholder='Last name..';
form_fields[4].placeholder='Email..';
form_fields[5].placeholder='Enter password..';
form_fields[6].placeholder='Re-enter Password..';


for (var field in form_fields){	
form_fields[field].className += ' form-control'
}
</script>

{% endblock content %}