berita/urls.py
from django.urls import path

from .views import *

app_name = 'berita'

urlpatterns = [
    path('', home, name='home'),
    path('create/', articleForm, name='create'),
    path('detail/<int:article_id>/', articleDetail, name='detail'),
    path('edit/<int:article_id>/', editArticle, name='edit'),
    path('delete/<int:article_id>', deleteArticle, name='delete')
]

kepepetpergi/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('berita/', include('berita.urls')),
    path('tambahData/', include('tambahData.urls')),
    path('pencarian/', include('pencarian.urls')),
    path('status/', include('status.urls')),
    path('formSaran/', include('formSaran.urls')),
    path('autentikasi/', include('autentikasi.urls')),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

berita/models.py
from django.db import models
from django.contrib.auth.models import User
from tinymce.models import HTMLField
# Create your models here.

class Article(models.Model):
    article_id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE,null=False, related_name='articles')
    date = models.DateField(auto_now=True)
    title = models.CharField(max_length=50, null=False)
    post = models.TextField(null=False)

    def get_short_post(self):
        return self.post[:100]

berita/forms.py
from django import forms
from tinymce.widgets import TinyMCE
from .models import *

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = [
            'user',
            'title',
            'post'
        ]
        widgets = {
            'user' : forms.HiddenInput()
        }

berita/views.py
from django.shortcuts import render
from newsapi.newsapi_client import NewsApiClient
from .forms import ArticleForm
from django.shortcuts import redirect

from .models import *

class Berita:
	def __init__(self, judul, isi, gambar, website, alamat):
		self.judul = judul
		self.isi = isi
		self.gambar = gambar
		self.website = website
		self.alamat = alamat

# Create your views here.
def home(request):
	beritas = []
	try:
		newsapi = NewsApiClient(api_key='6fbbdcf18b614bccb89f053575af762b')
		news = newsapi.get_top_headlines(q='covid', country='id')
		for item in news['articles']:
			judul = item['title']
			isi = item['description']
			gambar = item['urlToImage']
			website = item['source']['name']
			alamat = item['url']
			berita = Berita(judul, isi, gambar, website, alamat)
			beritas.append(berita)
	except:
		pass
	
	articles = Article.objects.all()

	response = {
		'beritas' : beritas,
		'articles' : articles
		}
	return render(request, 'berita/home.html',response)

def articleForm(request):
	if(request.method == 'POST'):
		form = ArticleForm(request.POST)
		if(form.is_valid()):
			form.save()
			return redirect('/berita')
	else:
		form = ArticleForm(initial={'user' : request.user})

	response = {
		'input_form' : form
	}

	return render(request, 'berita/articleForm.html', response)

def articleDetail(request, article_id):
	article = Article.objects.get(article_id=article_id)

	response = {
		'article' : article
	}

	return render(request, 'berita/detail.html', response)

def editArticle(request, article_id):
	article = Article.objects.get(article_id=article_id)
	if(request.method == 'POST'):
		form = ArticleForm(request.POST, instance=article)
		if(form.is_valid()):
			form.save()
			return redirect('/berita')
	else:
		form = ArticleForm(instance=article)

	response = {
		'input_form' : form
	}

	return render(request, 'berita/articleForm.html', response)

def deleteArticle(request, article_id):
	article = Article.objects.get(article_id=article_id)
	article.delete()

	return redirect('/berita')

berita/templates/berita/articleForm.html
{% extends 'base.html' %}
{% load static %}
<!-- Required meta tags -->

{% block meta %}
<title>{{page_title}}</title>
{% endblock meta %}

{% block footer_style %}relative{% endblock %}

{% block content %}
  <div class="d-flex flex-column my-3 berita-content">
  <h1 style="text-align: center;"> {{page_title}} </h1>
  <div class="card my-5 border-custom">
    <div class="card-body p-5">
        <form method='POST' class='form-custom'>
          {% csrf_token %}
          {{ input_form }}
          <button class="btn btn-primary" type="submit">Kirim</button>
        </form>
      </div>
    </div>
  </div>
{% endblock content %}

berita/templates/berita/detail.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Berita</title>
{% endblock meta %}

{% block footer_style %}relative{% endblock %}

{% block content %}

  <div class="d-flex flex-column my-3 berita-content">
    <h1 style="text-align: center;"> {{article.title}} </h1>
    {% if article.user == user %}
    <div class='article-edit-container'>
      <a href="{% url 'berita:delete' article_id=article.article_id %}"><button class="btn btn-danger">Hapus Artikel</button></a>
      <a href="{% url 'berita:edit' article_id=article.article_id %}"><button class="btn btn-danger">Edit Artikel</button></a>
    </div>
    {% endif %}
    <div class="card my-5 border-custom">
      <div class="card-body p-5">
        <div class="card my-3 border-custom2">
          <div class="card-body child-card">
              {{ article.post|linebreaksbr }}
          </div>
        </div>
        <p class="float-right">Ditulis oleh {{ article.user.get_short_name }} </p>
        <br>
        <p class="float-right">{{ article.date }} </p>
      </div>
    </div>

  </div>
{% endblock content %}

berita/templates/berita/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Berita</title>
{% endblock meta %}

{% block footer_style %}relative{% endblock %}

{% block content %}
  <div class="d-flex flex-column my-3 berita-content">
    <h1 style="text-align: center;"> Headline </h1>

    {% for berita in beritas %}
    <div class="card my-5 border-custom">
      <div class="card-body p-5">
        <h3 class="card-title">{{berita.judul}}</h3>
        <div class="content-image">
          <img class="img-fluid image-custom"src="{{berita.gambar}}">
        </div>
        <div class="card my-3 border-custom2">
          <div class="card-body child-card">
            <p class="card-text">{{berita.isi}}</p>
          </div>
        </div>
        <p class="float-right">Baca selengkapnya di <a href="{{berita.alamat}}" target="_blank" class="card-link">{{berita.website}}</a></p>
      </div>
    </div>
    {% endfor %}
    
    <h1 style="text-align: center;"> Artikel </h1>
    <div id='create-article'>
      {% if user.is_authenticated %}
      <a href="{% url 'berita:create' %}"><button class="btn btn-primary">Tulis Artikel</button></a>
      {% else %}
      <div class="panel panel-default">
        <div class="panel-body">
          Login supaya bisa menulis artikel
        </div>
      </div>
      {% endif %}
    </div>

    {% for article in articles %}
    <div class="card my-5 border-custom">
      <div class="card-body p-5">
        <h3 class="card-title">{{article.title}}</h3>
        {% if article.user == user %}
        <div class='article-edit-container'>
          <a href="{% url 'berita:delete' article_id=article.article_id %}"><button class="btn btn-danger">Hapus Artikel</button></a>
          <a href="{% url 'berita:edit' article_id=article.article_id %}"><button class="btn btn-danger">Edit Artikel</button></a>
        </div>
        {% endif %}
        <div class="card my-3 border-custom2">
          <div class="card-body child-card">
            {{ article.get_short_post|linebreaksbr }}
          </div>
        </div>
        <p class="float-right"><a href="{% url 'berita:detail' article_id=article.article_id %}" target="_blank" class="card-link">Klik ini untuk baca lengkapnya..</a></p>
        <br>
        <p class="float-right">Ditulis oleh {{ article.user.get_short_name }} </p>
        <br>
        <p class="float-right">{{ article.date }} </p>
      </div>
    </div>
    {% endfor %}
  </div>
{% endblock content %}